version: '3.8'
services:
  backend:
    build:
      context: ../backend
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - postgres
      - elasticsearch
  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
  elasticsearch:
    # No official Fedora Elasticsearch image; using upstream image
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200" 